name: Despliegue flutter

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.0

    - name: Dependencias proyecto
      run: flutter pub get

    - name: Test
      run: flutter test

    - name: Build AAB
      run: flutter build appbundle

    - name: Build APK
      run: flutter build apk --split-per-abi

    - name: Create Release
      run: gh release create ${{ github.ref_name }}
    - name: Upload files AAB
      run: gh release upload ${{ github.ref_name }} ./build/app/outputs/bundle/release/*
    - name: Upload files APK
      run: gh release upload ${{ github.ref_name }} ./build/app/outputs/flutter-apk/*
