name: Despliegue flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.0

    - name: Dependencias proyecto
      run: flutter pub get

    - name: Test
      run: flutter test

    - name: Build AAB
      run: flutter build appbundle

    - name: Build APK
      run: flutter build apk --split-per-abi
    - name: listado
      run: ls -l

    - name: Create Release
      run: gh release create testrelease
    - name: Upload files
      run: gh release upload ./build/*
