name: Despliegue flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Create Release
      run: echo "${GH_TOKEN}" | gh auth login --with-token
      run: gh release create testrelease
    - name: Upload files
      run: gh release upload testrelease .package.json
