name: Despliegue flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Upload files
      run: gh release upload testrelease ./README.org
