name: Despliegue flutter

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Create Release
      run: gh release create ${{ github.ref_name }}
    - name: Upload files AAB
      run: gh release upload ${{ github.ref_name }} ./README.org
