name: Despliegue flutter en Windows

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.0

    - name: Dependencias proyecto
      run: flutter pub get

    - name: Test
      run: flutter test

    - name: Build Exe
      run: flutter build windows

    - name: Upload files windows
      run: gh release upload ${{ github.ref_name }} .\build\windows\x64\runner\Release\integracion_continua_3.exe
